apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphql-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: letsencrypt
spec:
  rules:
     - http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: graphql-sv
                port:
                  number: 3000
    
  tls:
    - secretName: nthu-lost-found-tls
      hosts:
        - nthu-lost-found.yikuo.dev

