apiVersion: v1
kind: Secret
metadata:
  name: graphql-google-secret
  labels:
    app: graphql
type: Opaque
data:
  service-account-file.json: "GOOGLE SERVICE ACCOUNT FILE BASE64"

# To create the secret from the service-account-file.json file, use
# kubectl create secret generic graphql-google-secret --from-file service-account-file.json
